cabal-version:      3.0
name:               HasChor
version:            0.1.0.1
synopsis:           Functional Choreographic Programming
license:            BSD-3-Clause
license-file:       LICENSE
author:             Gan Shen
maintainer:         Gan Shen <gan_shen@icloud.com>
copyright:          (c) Gan Shen 2026
category:           Concurrency
description:
    HasChor is a library for functional choreographic programming in Haskell.
    See the README.md for more information.

tested-with:
    GHC == 9.6.7

extra-doc-files:
    README.md

source-repository head
    type:     git
    location: https://github.com/gshen42/HasChor

source-repository this
    type:     git
    location: https://github.com/gshen42/HasChor
    tag:      v0.1.0.1

library
    hs-source-dirs:   src
    ghc-options:      -Wall
    default-language: GHC2021
    exposed-modules:
        Choreography
    other-modules:
        Choreography.Choreo
    build-depends:
        base                 ^>= 4.18.3,
        binary               ^>= 0.8.9,
        bytestring           ^>= 0.11.5.4,
        http-client          ^>= 0.7.19,
        servant              ^>= 0.20.2,
        servant-client       ^>= 0.20.2,
        servant-server       ^>= 0.20.2,
        template-haskell     ^>= 2.20.0,
        unordered-containers ^>= 0.2.20,
        warp                 ^>= 3.3.31,
        singletons           ^>= 3.0.4,
        singletons-base      ^>= 3.2,
