cabal-version:      3.0
name:               HasChor-examples
version:            0.1.0.1
synopsis:           Examples for HasChor

tested-with:
    GHC == 9.6.7

executable concur-server
    hs-source-dirs:   explicit-parallel/concur-server
    main-is:          Main.hs
    default-language: GHC2021
    build-depends:
        base                 ^>= 4.18.3,
        HasChor

executable microservices
    hs-source-dirs:   explicit-parallel/microservices
    main-is:          Main.hs
    default-language: GHC2021
    build-depends:
        base                 ^>= 4.18.3,
        HasChor

executable quorum-voting
    hs-source-dirs:   explicit-parallel/quorum-voting
    main-is:          Main.hs
    default-language: GHC2021
    build-depends:
        base                 ^>= 4.18.3,
        stm                  ^>= 2.5.1,
        HasChor

executable nshaped
    hs-source-dirs:   explicit-parallel/nshaped
    main-is:          Main.hs
    default-language: GHC2021
    build-depends:
        base                 ^>= 4.18.3,
        stm                  ^>= 2.5.1,
        HasChor

executable display-decrypt
    hs-source-dirs:   explicit-parallel/display-decrypt
    main-is:          Main.hs
    default-language: GHC2021
    build-depends:
        base                 ^>= 4.18.3,
        HasChor

executable twice-X
    hs-source-dirs:   explicit-parallel/twice-X
    main-is:          Main.hs
    default-language: GHC2021
    build-depends:
        base                 ^>= 4.18.3,
        HasChor

executable buy-items
    hs-source-dirs:   explicit-parallel/buy-items
    main-is:          Main.hs
    default-language: GHC2021
    build-depends:
        base                 ^>= 4.18.3,
        unordered-containers ^>= 0.2.20,
        transformers         ^>= 0.6.1.0,
        HasChor

executable shared-stream
    hs-source-dirs:   explicit-parallel/shared-stream
    main-is:          Main.hs
    default-language: GHC2021
    build-depends:
        base                 ^>= 4.18.3,
        HasChor

executable image-classification
    hs-source-dirs:   explicit-parallel/image-classification
    main-is:          Main.hs
    default-language: GHC2021
    build-depends:
        base                 ^>= 4.18.3,
        stm                  ^>= 2.5.1,
        unordered-containers ^>= 0.2.20,
        HasChor

executable quorum-voting-choreo2
    hs-source-dirs:   explicit-parallel/quorum-voting-choreo2
    main-is:          Main.hs
    default-language: GHC2021
    build-depends:
        base                 ^>= 4.18.3,
        stm                  ^>= 2.5.1,
        HasChor
